# Generated by Django 4.2.2 on 2023-06-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_auto_20230617_0121"),
    ]

    operations = [
        migrations.RemoveField(model_name="wallet", name="user",),
        migrations.AlterField(
            model_name="wallet", name="coins", field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
