# Generated by Django 4.2.2 on 2023-06-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_remove_wallet_user_alter_wallet_coins_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
